version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    networks:
      - k6-net
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    platform: linux/amd64  #only if you uses mac with arm architecture
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    networks:
      - k6-net

  k6:
    image: loadimpact/k6
    container_name: k6
    platform: linux/amd64  #only if you uses mac with arm architecture
    depends_on:
      - api
    entrypoint: >
      k6 run /scripts/test.js
      --out influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6/test.js:/scripts/test.js
    networks:
      - k6-net

networks:
  k6-net:
    driver: bridge
