# use base image Node.js
FROM node:14

# isntall simpleapi working directory
WORKDIR /usr/src/app

# copy package.json and package-lock.json
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Open port
EXPOSE 3000

# Run app
CMD ["node", "api.js"]
